CREATE TABLE IF NOT EXISTS users(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(250),
    email varchar(254),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);