CREATE TABLE IF NOT EXISTS users(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(250),
    email varchar(254),
    CONSTRAINT pk_user PRIMARY KEY (id),
    CONSTRAINT UQ_USER_EMAIL UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS categories(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    name varchar(50),
    CONSTRAINT pk_categories PRIMARY KEY (id),
    CONSTRAINT UQ_CATEGORY_NAME UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS events(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar(120) NOT NULL,
    annotation varchar(2000),
    description varchar(7000) NOT NULL,
    cat_id bigint NOT NULL,
    participant_limit integer NOT NULL,
    state varchar(20) NOT NULL,
    paid boolean NOT NULL,
    event_date timestamp WITHOUT TIME ZONE NOT NULL,
    created_on timestamp WITHOUT TIME ZONE NOT NULL,
    published_on timestamp WITHOUT TIME ZONE,
    initiator_id bigint NOT NULL,
    latitude float NOT NULL,
    longitude float NOT NULL,
    request_moderation boolean NOT NULL,
    confirmed_participants integer,
    CONSTRAINT pk_events PRIMARY KEY (id),
    CONSTRAINT FK_EVENTS_ON_CAT FOREIGN KEY (cat_id) REFERENCES categories (id),
    CONSTRAINT FK_EVENTS_ON_USERS FOREIGN KEY (initiator_id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS participation_request(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created timestamp WITHOUT TIME ZONE NOT NULL,
    event_id bigint NOT NULL,
    requester_id bigint NOT NULL,
    status varchar(20),
    CONSTRAINT pk_participation_request PRIMARY KEY (id),
    CONSTRAINT FK_PARTICIPATION_REQUEST_ON_EVENTS FOREIGN KEY (event_id) REFERENCES events (id),
    CONSTRAINT FK_PARTICIPATION_REQUEST_ON_USERS FOREIGN KEY (requester_id) REFERENCES users (id),
    CONSTRAINT UQ_PARTICIPANT_PER_EVENT UNIQUE (requester_id, event_id)
);

CREATE TABLE IF NOT EXISTS compilations(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    title varchar(50) NOT NULL,
    pinned boolean NOT NULL,
    CONSTRAINT pk_compilations PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS compilation_event(
    compilation_id bigint NOT NULL,
    event_id bigint NOT NULL,
    CONSTRAINT UQ_EVENT_PER_COMPILATION PRIMARY KEY (compilation_id, event_id),
    CONSTRAINT FK_COMPILATION_EVENT_ON_COMPILATIONS FOREIGN KEY (compilation_id) REFERENCES compilations(id),
    CONSTRAINT FK_COMPILATION_EVENT_ON_EVENTS FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE IF NOT EXISTS comments(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    text varchar(2000) NOT NULL,
    user_id bigint NOT NULL,
    event_id bigint NOT NULL,
    state varchar(20) NOT NULL,
    created_on timestamp WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_comments PRIMARY KEY (id),
    CONSTRAINT FK_COMMENTS_ON_USERS FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT FK_COMMENTS_ON_EVENTS FOREIGN KEY (event_id) REFERENCES events (id)
)