version: '3.8'
services:
  stats-server:
    build: stats/stats-service
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres
    container_name: postgres-ewm-stats-db
    volumes:
      - stats_postgres_data:/var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"
      - "8081:8081"
    depends_on:
      - ewm-main-db
      - stats-server
    environment:
      - STAT_SERVER_URL=http://stats-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-main-db:5432/ewm-main
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  ewm-main-db:
    image: postgres
    container_name: postgres-ewm-main-db
    volumes:
      - main_postgres_data:/var/lib/postgresql/data/
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-main
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

volumes:
  stats_postgres_data:
  main_postgres_data:
