version: '3.8'
services:
  stats-server:
    build: stats/stats-service
    container_name: ewm-stats-server
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-stats
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  stats-db:
    image: postgres
    container_name: postgres-ewm-stats-db
    volumes:
      - stats_postgres_data:/var/lib/postgresql/data/
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-stats
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  ewm-service:
    build: main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"

  ewm-db:
    image: postgres

volumes:
  stats_postgres_data:
