CREATE TABLE IF NOT EXISTS endpoints  (
                          id bigint primary key generated by default as identity,
                          app varchar(255),
                          uri varchar,
                          ip varchar,
                          request_time timestamp without time zone
);